---
zfs_user_datasets:
      - "home/{{ user }}"
      - "home/{{ user }}/.config"
      - "home/{{ user }}/.local"
      - "home/{{ user }}/.local/share"

default_packages:
      - vim
      - git
      - rsync
      - dosfstools
      - openssh-server
      - curl
      - wget
      - apt-file
      - software-properties-common
      - apt-transport-https
      - zsh
      - zsh-antigen
      - irssi
      - lynx
      - elinks
      - lm-sensors
      - net-tools
      - screen
      - tmux
      - sysstat
      - htop
      - iotop
      - ripgrep
      - nmap
      - iftop
      - tcpdump
      - smartmontools
      - chrony
      - dnsutils

remove_packages:
      - systemd-timesyncd
      - ntp
      - ntpsec
      - openntpd
